### PR TITLE
Windows take 2

### PR DESCRIPTION
**Pull request by manics**
We finally have some Windows test builds https://github.com/manics/conda-zeroc-ice36-python/pull/new/windows-take-2
Install with `conda install -c ome -c ome/label/testing omero-py`

Merge this, tag as `3.6.5-5`, and we should have a release build

### CODE REVIEW

**Comment by emilroz** [comment]
At the moment install does not work for me:

```
(omero-py) C:\Users\emilr>conda install -c ome -c ome/labels/testing omero-py
Solving environment: \
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/ome/labels/testing
It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.
If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
failed
PackagesNotFoundError: The following packages are not available from current channels:
  - omero-py
  - zeroc-ice36-python
Current channels:
  - https://conda.anaconda.org/ome/win-64
  - https://conda.anaconda.org/ome/noarch
  - https://conda.anaconda.org/ome/labels/testing/win-64
  - https://conda.anaconda.org/ome/labels/testing/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch
```

Do I need to adjust config, etc?

**Comment by manics** [comment]
Sorry, there's a typo (I've fixed the description). It should be `ome/label/testing`, no `s`

**Comment by emilroz** [comment]
The install works `conda install -c ome -c ome/label/testing omero-py zeroc-ice36-python`:

```
(omero-py) C:\Users\emilr>conda list
# packages in environment at C:\Users\emilr\Anaconda3\envs\omero-py:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
bzip2                     1.0.8                he774522_0
ca-certificates           2020.1.1                      0
certifi                   2019.11.28               py36_1
expat                     2.2.5                he025d50_0
freetype                  2.9.1                ha9979f8_1
future                    0.18.2                   py36_0
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2020.0                      166
jpeg                      9b                   hb83a4c4_2
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.1.0                h56a325e_0
mkl                       2020.0                      166
mkl-service               2.3.0            py36hb782905_0
mkl_fft                   1.0.15           py36h14836fe_0
mkl_random                1.1.0            py36h675688f_0
numpy                     1.18.1           py36h93ca92e_0
numpy-base                1.18.1           py36hc3f5095_1
olefile                   0.46                     py36_0
omero-py                  5.6.2                      py_0    ome
openssl                   1.1.1e               he774522_0
pillow                    7.0.0            py36hcc1f983_0
pip                       20.0.2                   py36_1
python                    3.6.10               h9f7ef89_1
setuptools                46.1.3                   py36_0
six                       1.14.0                   py36_0
sqlite                    3.31.1               he774522_0
tk                        8.6.8                hfa6e2cd_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wheel                     0.34.2                   py36_0
wincertstore              0.2              py36h7fe50ca_0
xz                        5.2.4                h2fa13f4_4
zeroc-ice36-python        3.6.5.test       py36h74a9793_4    ome/label/testing
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0
```

but the omero-py looks unhappy:
```
(omero-py) C:\Users\emilr>ipython
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import omero.clients
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-a48cccdcf19e> in <module>()
----> 1 import omero.clients

ModuleNotFoundError: No module named 'omero.clients'

In [2]: import omero

In [3]: from omero.gateway import BlitzGateway
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-4d7dd83e7852> in <module>()
----> 1 from omero.gateway import BlitzGateway

ModuleNotFoundError: No module named 'omero.gateway'
```

**Comment by manics** [comment]
I've already opened a couple of omero-py issues for Windows:
- https://github.com/ome/omero-py/issues/200
- https://github.com/ome/omero-py/issues/201

If you spot any more problems please open additional issues

**Comment by joshmoore** [comment]
> but the omero-py looks unhappy:

@emilroz: pretty sure this is the standard Ice import issue _a la_ https://github.com/ome/omero-py/issues/179 Start with `import omero` and perhaps `import omero.all` and things should work. 

Getting this tagged and released so others can help with testing, and then we can iterate on top of it.

**Comment by joshmoore** [comment]
@manics : does this also help with https://github.com/conda-forge/zeroc-ice-feedstock/issues/3 ?

**Comment by manics** [comment]
Sadly not. Conda-forge has it's own infrastructure for setting up builds on travis/azure/appveyor so although this PR shows its possible to build on Windows it doesn't help with setting up the infrastructure in the way that conda-forge requires.

**Pull request merged**
